env:
  browser: true
  es2020: true
  node: true
extends:
  - plugin:coffee/eslint-recommended
  - plugin:coffee/import
  - plugin:import/recommended
  - plugin:meteor/recommended
  - plugin:coffee/react-recommended
  - plugin:coffee/disable-incompatible
globals:
  $: readonly
  _: readonly
  s: readonly # underscore.string
  Blaze: readonly
  BrowserPolicy: readonly
  FileCollection: readonly
  JSDOM: readonly
  Kadira: readonly
  Meteor: readonly
  Modal: readonly
  ReactiveDict: readonly
  ReactiveVar: readonly
  Router: readonly
  Session: readonly
  Subscribe: readonly
  SubsManager: readonly
  Template: readonly
  Tracker: readonly
  WebApp: readonly
  # Coauthor databases
  Emoji: readonly
  EmojiMessages: readonly
  Files: readonly
  Groups: readonly
  Tags: readonly
  Messages: readonly
  MessagesDiff: readonly
  MessagesParent: readonly
  Notifications: readonly
  # Global functions that should be converted to imports
  accessibleGroups: readonly
  accessibleGroupNames: readonly
  accessibleMessagesQuery: readonly
  allUsernames: readonly
  amCoauthor: readonly
  atMentions: readonly
  atRe: readonly
  canAdmin: readonly
  canCoauthorsMod: readonly
  canDelete: readonly
  canEdit: readonly
  canImport: readonly
  canMaybeParent: readonly
  canMinimize: readonly
  canParent: readonly
  canPin: readonly
  canPost: readonly
  canPrivate: readonly
  canProtect: readonly
  canPublish: readonly
  canReply: readonly
  canUndelete: readonly
  canUnpin: readonly
  canUnpublish: readonly
  canUnminimize: readonly
  canSee: readonly
  canSuper: readonly
  canSuperdelete: readonly
  capitalize: readonly
  defaultFormat: readonly
  deleteFile: readonly
  displayUser: readonly
  displayUserLastName: readonly
  escapeGroup: readonly
  escapeRegExp: readonly
  escapeUser: readonly
  fileAbsoluteUrlPrefix: readonly
  fileType: readonly
  fileUrlPattern: readonly
  fileUrlPrefix: readonly
  findFile: readonly
  findGroup: readonly
  findMessage: readonly
  findMessageParent: readonly
  findMessageRoot: readonly
  findUser: readonly
  findUsername: readonly
  fullMemberOfGroup: readonly
  groupAnonymousRoles: readonly
  groupData: readonly
  groupFullMembers: readonly
  groupMembers: readonly
  groupPartialMembers: readonly
  groupPartialMessagesWithRole: readonly
  groupRoleCheck: readonly
  groupSortedBy: readonly
  groupVisible: readonly
  haveExplicitAccess: readonly
  highlight: readonly
  idRegex: readonly
  internalFileAbsoluteUrlPrefix: readonly
  internalFileUrlPrefix: readonly
  linkToAuthor: readonly
  linkToSort: readonly
  linkify: readonly
  listToTags: readonly
  markdown: readonly
  markdownInline: readonly
  marked: readonly # not actually used
  maybeAddRootsToQuery: readonly
  memberOfGroup: readonly
  memberOfGroups: readonly
  memberOfThread: readonly
  message2group: readonly
  message2root: readonly
  messageReaders: readonly
  messageRoleCheck: readonly
  messagesBy: readonly
  messagesByQuery: readonly
  messagesTaggedQuery: readonly
  notifyMessageUpdate: readonly
  pathFor: readonly
  pluralize: readonly
  readableFiles: readonly
  rootRoleCheck: readonly
  routeGroup: readonly
  routeGroupOrWild: readonly
  routeMessage: readonly
  routeSortBy: readonly
  sanitize: readonly
  setTitle: readonly
  sortedGroupFullMembers: readonly
  sortedGroupPartialMembers: readonly
  titleOrUntitled: readonly
  titleSort: readonly
  undeletedMessagesQuery: readonly
  unescapeGroup: readonly
  unescapeUser: readonly
  url2file: readonly
  url2internalFile: readonly
  urlFor: readonly
  urlToInternalFile: readonly
  urlToFile: readonly
  userSortKey: readonly
  validGroup: readonly
  validUsername: readonly
  wildGroup: readonly
ignorePatterns:
  - .meteor
parser: eslint-plugin-coffee
parserOptions:
  ecmaFeatures:
    globalReturn: true
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - coffee
  - import
  - meteor
  - react
rules:
  linebreak-style:
    - error
    - unix
  coffee/no-inner-declarations: off
  coffee/no-unused-vars:
    - error
    - args: none  # allow callbacks of the form (e) -> ...not using e...
  coffee/no-useless-escape: off
  import/default: off
  import/no-named-as-default-member: off
  react/no-unescaped-entities:
    - warn
    - forbid: ['>', '"', '}']
  react/prop-types: off
  react/react-in-jsx-scope: off
  meteor/eventmap-params:
    - error
    - eventParamName: e
      templateInstanceParamName: t
  meteor/no-session: off
  meteor/no-zero-timeout: off
  meteor/audit-argument-checks:
    - error
    - checkEquivalents:
      - checkId
settings:
  import/ignore:
    - node_modules
  import/resolver:
    meteor:
      extensions:
        - .coffee
        - .js
  react:
    version: detect
