require 'codemirror/mode/markdown/markdown.js'
require 'codemirror/mode/xml/xml.js'
require 'codemirror/mode/meta.js'
require 'codemirror/mode/stex/stex.js'
require 'codemirror/keymap/vim.js'
require 'codemirror/keymap/emacs.js'
require 'codemirror/addon/dialog/dialog.js'
require 'codemirror/addon/edit/matchbrackets.js'
require 'codemirror/addon/edit/continuelist.js'
require 'codemirror/addon/fold/foldcode.js'
require 'codemirror/addon/fold/foldgutter.js'
require 'codemirror/addon/fold/markdown-fold.js'
require 'codemirror/addon/fold/xml-fold.js'
require 'codemirror/addon/mode/overlay.js'
require 'codemirror/addon/search/searchcursor.js'
require 'codemirror/addon/search/search.js'
require 'codemirror/addon/search/jump-to-line.js' # alt-G
require 'codemirror/addon/selection/active-line.js'
